site_name: Sage Monolith документация
# Настройка темы Material
theme:
 name: material
 custom_dir: docs/img
 language: ru
 features:
   - toc.integrate
   - navigation.tabs
   - navigation.sections
   - navigation.indexes
 palette:
   scheme: default  # светлая тема
   primary: indigo  # основной цвет
   accent: blue     # акцентный цвет
 icon:
   repo: fontawesome/brands/github  # иконка репозитория (если есть)
# Навигация с иконками (корректный синтаксис)
nav:
 - Главная:
     - index.md
 - О проекте:
     - about.md
 - Черногория:
     - montenegro.md 
 - Италия:
     - italy.md